services:
  _defaults:
    public: false
    autoconfigure: true

  Uv\File\FileAssistant:
    autowire: true

  Uv\File\Components\Image\ImageStyle:
    autowire: true

  Uv\File\Twig\ImageStyleExtension:
    autowire: true

  uv.file.file_assistant:
    alias: Uv\File\FileAssistant
    public: true

  Uv\File\Events\FileUploadSubscriber:
    autowire: true
    tags:
      - { name: doctrine.event_subscriber }