#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_preview:
  path: /preview
  controller: App\Controller\DefaultController::preview
#PAGE ROUTES
page_list:
  path: /{_locale}/page
  controller:  App\Controller\PageController::list
  requirements:
    _locale: '%app.locales%'

page_list_direct:
  path: /page
  controller:  App\Controller\PageController::list

page_add:
  path: /{_locale}/page/add
  controller:  App\Controller\PageController::add
  requirements:
    _locale: '%app.locales%'


page_view:
  path: /{_locale}/page/{id}
  controller:  App\Controller\PageController::view
  requirements:
    id: '\d+'
    _locale: '%app.locales%'

page_add_translation:
  path: /{_locale}/page/{id}/translation
  controller:  App\Controller\PageController::translation
  requirements:
    id: '\d+'
    _locale: '%app.locales%'

page_comments:
  path: /page/{id}/comments
  defaults: { _controller: PageBundle:Page:comments }
  requirements:
    id: '\d+'

page_edit:
  path: /{_locale}/page/{id}/edit
  controller:  App\Controller\PageController::edit
  requirements:
    id: '\d+'
    _locale: '%app.locales%'
#
page_delete:
  path: /page/{id}/delete
  defaults: { _controller: PageBundle:Page:remove }
  requirements:
    id: '\d+'

page_search:
  path: /search
  defaults: { _controller: PageBundle:Page:search }

#TERM ROUTES
term_list:
  path: /term
  defaults : { _controller: App\Controller\TermController::list }

term_add:
  path: /term/add
  defaults : { _controller: App\Controller\TermController::add }

term_view:
  path: /{_locale}/term/{id}
  defaults : { _controller: App\Controller\TermController::view }
  requirements:
    id: '\d+'
    _locale: '%app.locales%'

term_edit:
  path: /term/{id}/edit
  defaults : { _controller: App\Controller\TermController::edit }
  requirements:
    id: '\d+'


term_delete:
  path: /term/{id}/delete
  defaults : { _controller: App\Controller\TermController::delete }
  requirements:
    id: '\d+'


#comments ROUTERS
comment_edit:
  path: /comment/{id}/edit
  defaults: { _controller: CommentBundle:Comment:edit }
  requirements:
    id: '\d+'
#
comment_delete:
  path: /comment/{id}/delete
  defaults: { _controller: CommentBundle:Comment:remove }
  requirements:
    id: '\d+'

comment_view:
  path: /{_locale}/comment/{id}
  defaults: { _controller: App\Controller\CommentController::view }
  requirements:
    id: '\d+'
    _locale: '%app.locales%'

#user

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout

register:
  path: /register
  defaults: { _controller: UserBundle:Security:register }

recover:
  path: /recover/{token}
  defaults: { _controller: UserBundle:Security:recover, token: null }


user:
  path: /user

user_password_recover:
  path: /user/recover-password
  defaults: { _controller: UserBundle:User:recoverPassword }